name: NADE
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.10
  - numpy
  - pandas
  - pytorch
  - pip
  - ffmpeg
  - tqdm
  - pip:
      - birdnetlib==0.17.2
      - librosa
      - tensorflow==2.16.1
      - tflite==2.10.0
      - resampy==0.4.3
